---
title: "Proj_Code_Analysis"
output:
  pdf_document: default
  html_document: default
date: "2025-03-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load("/Users/ellathomasson/Documents/STAT 4996/NSDUH_2023.Rdata")
library(dplyr)
library(ggplot2)
library(kableExtra)
```

```{r}
povertyDepData<-puf2023_102124[,c("AMDELT",
                                  "POVERTY3", 
                                  "NEWRACE2",
                                  "IRHHSIZ2",
                                  "MOVSINPYR2",
                                  "MEDICARE",
                                  "CAIDCHIP",
                                  "CHAMPUS",
                                  "PRVHLTIN",
                                  "GRPHLTIN",
                                  "IREDUHIGHST2",
                                  "WRKSTATWK2", 
                                  "CIGREC", 
                                  "HLTINALC", 
                                  "HLTINDRG", 
                                  "CIGREC"
)]

names(povertyDepData)<-c("lifetimeDepression",
                         "povertyThreshold",
                         "race",
                         "householdSize",
                         "timesMovedPastYear",
                         "medicare",
                         "medicaid_chip",
                         "govtHealthcare",
                         "privateHealthcare",
                         "employer_unionHealthcare",
                         "highestEducationCompleted",
                         "workStatusPastWeek",
                         "LastSmoke", 
                         "AlcHealthCare",
                         "DrgHealthCare", 
                         "timeSinceLastCigarette")
```


# analysis


```{r}
sum(is.na(povertyDepData$lifetimeDepression)) / nrow(povertyDepData)
```


## cleaning 

```{r}
povertyDepData %>%
  group_by(timeSinceLastCigarette) %>%
  summarize(
    count = n()
  )
```


```{r}
povertyDepData_cleaned <- povertyDepData[!is.na(povertyDepData$lifetimeDepression), ]

povertyDepData_cleaned = povertyDepData_cleaned[povertyDepData_cleaned$timesMovedPastYear < 4,]
povertyDepData_cleaned <- povertyDepData_cleaned[!is.na(povertyDepData_cleaned$povertyThreshold), ]

povertyDepData_cleaned = povertyDepData_cleaned[povertyDepData_cleaned$AlcHealthCare < 3,]
povertyDepData_cleaned = povertyDepData_cleaned[povertyDepData_cleaned$DrgHealthCare < 3,]

povertyDepData_cleaned = povertyDepData_cleaned[,c("lifetimeDepression","race","LastSmoke","timesMovedPastYear",
                                                   "highestEducationCompleted","medicare","AlcHealthCare","DrgHealthCare","timeSinceLastCigarette")]



povertyDepData_cleaned$timeSinceLastCigarette <- as.numeric(povertyDepData_cleaned$timeSinceLastCigarette)


povertyDepData_cleaned <- povertyDepData_cleaned %>%
  mutate(
    timeSinceLastCigarette = case_when(
      timeSinceLastCigarette == 1 ~ "Past 30 Days",
      timeSinceLastCigarette %in% c(2, 8, 19) ~ "Past Year",
      timeSinceLastCigarette %in% c(3, 14, 29, 39) ~ "Past 3 Years", 
      timeSinceLastCigarette%in% c(4,9) ~ "More than 3 Years",
      timeSinceLastCigarette == 91 ~ "Never Used",
      TRUE ~ as.character(timeSinceLastCigarette)  # Keep original value (converted to character)
    )
  )


```

Current Explan Variables: "race","LastSmoke","timesMovedPastYear","highestEducationCompleted","medicare","AlcHealthCare","DrgHealthCare"

## train-test split 

```{r}
povertyDepData_cleaned$lifetimeDepression <- ifelse(povertyDepData_cleaned$lifetimeDepression == 1, 1, 0) # 1 is "has had depression"
```


```{r}

sample_size <- floor(0.7 * nrow(povertyDepData_cleaned))
train_indices <- sample(seq_len(nrow(povertyDepData_cleaned)), sample_size)

train_data <- povertyDepData_cleaned[train_indices, ]
test_data <- povertyDepData_cleaned[-train_indices, ]

```


```{r}
logistic_model <- glm(
  lifetimeDepression ~ race + LastSmoke + timesMovedPastYear + highestEducationCompleted + medicare + AlcHealthCare + DrgHealthCare + timeSinceLastCigarette, 
  data = train_data, 
  family = binomial(link = "logit")
)
```


```{r}
predictions <- predict(logistic_model, newdata = test_data, type = "response")
predicted_class <- ifelse(predictions > 0.2, 1, 0)

hist(predictions)
```


```{r}
confusion_matrix <- table(
  Actual = test_data$lifetimeDepression, 
  Predicted = predicted_class
)
print("Confusion Matrix:")
print(confusion_matrix)


tpr = 531/(546+531)
tnr = 2898 / (1673+2898) 

tpr
tnr
```

```{r}
accuracy <- sum(diag(confusion_matrix)) / sum(confusion_matrix)
print(paste("Accuracy:", round(accuracy, 4))) 
```


The fact that the classes are unequal in size seems to be causing issues. This may need to be addressed sooner rather than later. 

Also, may need to try more complex model? 



